[tools]
golang = "1.25.5"
protoc-gen-go-grpc = "1.5.1"
protoc-gen-go = "1.36.11"
protoc = "29.3"
helm = "3.15.1"

[settings]
pin = true

[tools."http:pgformatter"]
# You can pin a specific version or use "latest"
version = "5.8"
# Tarball URL from the README (v${version}.tar.gz)
url = "https://github.com/darold/pgFormatter/archive/refs/tags/v{{version}}.tar.gz"
strip_components = 1

# Make `mise ls-remote http:pgformatter` work using GitHub releases
version_list_url = "https://api.github.com/repos/darold/pgFormatter/releases"
version_json_path = ".[].tag_name"
